### PR TITLE
Invalid entity descriptions when using multiple persistent store coordinators.

### PR DESCRIPTION
**Pull request by AnthonyMDev**
The entity descriptions from one PSC cannot be used with another PSC. This PR makes the `cachedEntityDescriptions` an associated value on the PSC so that each PSC will have a separate cache.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Thanks for this! Please let me know as soon as you push a new version with this fix!

**Comment by vmartinelli** [comment]
Thank you for catching this bug. :) I am using the previous version of **ACD** and I did not have how to test the latest version extensively. A new build was generated with your fix. Please let me know if you find more bugs. Thank you again.

**Comment by AnthonyMDev** [comment]
Thank you so much!

**Comment by AnthonyMDev** [comment]
Version `5.0-beta1` has these changes reverted, which is causing this bug to reappear.

**Comment by vmartinelli** [comment]
I did a new commit about this issue. Please let me know if it does not solve the problem.

**Comment by AnthonyMDev** [comment]
That seems to work.

**Pull request merged**
