### PR TITLE
Table.toArray() conversion fix

### PR DESCRIPTION
**Pull request by skyylex**
I've found that conversion toArray in the Table extension doesn't work. The root cause is in the 

    if let objects = self.executeFetchRequest(fetchRequest) as? [T]

Such conversion will not work in Swift 1.2 . Some thoughts about that can be found in this issue http://stackoverflow.com/questions/24422840/convert-nsarray-to-swift-arrayt

Unfortunately, double casting with "as" also doesn't work for generics, so I used manual unwrapping for the each of elements. Indeed, not the best solution, but it works.

### CODE REVIEW

**Comment by vmartinelli** [comment]
Hello.

I'm trying to understand, but if there is an error in this peace of code the whole framework will not work at all, but AlecrimCoreData is working.

Can you provide more details about the circumstances where this error occurs and the steps to reproduce it?

Thank you.

**Comment by skyylex** [comment]
Yep. Please take a look on [this](https://github.com/skyylex/AlecrimExperiment) sample project where such behavior I have found

**Comment by vmartinelli** [comment]
I compiled and tested your project and your are right. The objects are not casted to `T`.

What I don't understand now is why in my own projects this does not happen.

This is a serious issue. Not from AlecrimCoreData, but it is, anyway. Thanks for your commitment, including to have created the test project.

I would like to suggest a shortest implementation:

```swift
    public func toArray() -> [T] {
        let fetchRequest = self.toFetchRequest()
        var results = [T]()
        
        if let objects = self.executeFetchRequest(fetchRequest) {
            // HAX: using `map:` because `self.executeFetchRequest(fetchRequest) as? [T]`
            // will not work in Swift 1.x in some circumstances
            results += objects.map { $0 as! T }
        }
        
        return results
    }
```

Thank you very much. :-)

**Comment by skyylex** [comment]
I'm glad that I was able to help.:) Your implementation is more "Swifty" and looks more expressive, let's put it as a solution. 

According to the issue I also think that this code if it can be compiled should work 100%. If it doesn't work and it is compiled without any warning this is a bug related to Swift compiler. I presume that Swift 2.0 will fix this issue. I will check and describe my results later.

**Pull request merged**
