### PR TITLE
Swift 3.0 Compatibility 

### PR DESCRIPTION
**Pull request by AnthonyMDev**
The previous Swift 3 migration branch was outdated and attempting to merge it with `develop` didn't work out very well. I've gone ahead and re-done the conversion based on the current `develop` branch. 

This does not include the conversion for ACDGen, only for `AlecrimCoreData`.

### CODE REVIEW

**Comment by alvinmeimoun** [comment]
Using your fork repository in my project (you saved my week i wan't to keep iOS 9 support), work greats ! (Tested on iOS 10 & 9.3)

**Comment by vmartinelli** [comment]
I'm thinking about to let your version to be the next version o **ACD** and the current beta branch to be postponed. What do you think?

(We'll need to update the docs and ensure the generated code from **ACDGen** will work, anyway.)

**Comment by AnthonyMDev** [comment]
@vmartinelli I think that's a great idea. This PF is functionally stable and is working in my production applications currently. If you can make the changes for @ACDGen, we should be good to go!

**Comment by AnthonyMDev** [comment]
Also, I this branch was just a migration of the current `develop` branch. So all of the beta features that are currently implemented in `develop` are included here.

**Comment by huangy10** [comment]
I love your job, and waiting for Swift 3 supports. :P

**Comment by v-silin** [comment]
Hi, all. Any update here? I just found this lib and really like to add it to my project.

**Comment by v-silin** [comment]
Could you fix build errors like these http://screencast.com/t/QrHkH0YG ?

**Comment by huangy10** [comment]
Hey, you can try this pr in advance before it is accepted. Just edit your Podfile, and change `pod ‘AlecrimCoreData’` into '    pod 'AlecrimCoreData', :git => 'https://github.com/AnthonyMDev/AlecrimCoreData.git', :branch => 'swift-3.0’
‘

This works for me.

Woody Huang
Tsinghua Universty

**Comment by glebus** [comment]
@v-silin this errors appears because your deployment target lower than iOS 10 and NSPersistentContainer is available only in iOS 10 and newer.

But anyway, @AnthonyMDev could you please add support iOS 9 in swift3 branch.

For example you can use @available attribute for checking deployment target version.

**Comment by AnthonyMDev** [comment]
I've already added iOS9 support on my fork. I can't add it to the swift3 branch here because I'm not an official contributor on this library. 

The actual maintainer of this repository has been notably inactive and nearly absent recently. Ive forked and if he doesn't push support for swift3 soon I'm likely going to just push my own pod version from my fork.

**Comment by glebus** [comment]
@AnthonyMDev Wow! This is great! Thank you!

By the way, have you tried it on iOS 8? :)

**Comment by AnthonyMDev** [comment]
I have not tested it specifically but I don't see why it wouldn't work.

**Comment by vmartinelli** [comment]
Well... I am the notably inactive and nearly absent maintainer of this repository (and the creator of **ACD**, by chance).

In my day job, I'm converting the company's apps to Swift 3 and trying to maintain the delivery schedule for new features and all that stuff you may know how it is.

My personal life has also been quite busy, having also lost someone I love very recently.

While I appreciate any contribution to the library (and I'm really very grateful for them), I have not had time to create a stable release for Swift 3 that support older operating systems. The @AnthonyMDev repository is covering this gap for now.

I hope to count on the understanding of all of you.

**Comment by AnthonyMDev** [comment]
@vmartinelli I am very sorry for your loss. We all can empathize with busy, stressful times in our careers and with difficult situations in our personal lives.

At the same time, this library has a huge number of followers that are relying on its stability. The timely release of compatibility with swift 3.0 is very important to a lot of people. Yes, my fork is available, but a lot of people aren't aware it exists still. This PR has 6 participants, and the library has over 600 stars. Many users aren't familiar with the advances capabilities of CocoaPods and might not even know how to depend upon my fork. Not having this functionality packaged and deployed has, in my opinion, a severe negative impact on the Alecrim community and the credibility of this library.

I completely understand going through periods in which you are unable to focus on open source projects, but when you have a library that is as widely used as this one, the correct response isn't to ask people to rely on forks; it is to seek assistance. I have personally extended the offer to assist in the maintenance of this library multiple times, and I feel that my contributions up to this point have adequately demonstrated my aptitude and good judgement. I'm sure there are other members of the ACD community who would have been willing to assist as well.

I don't mean to start an argument; I'm only saying any of this because ACD is a very important part of my toolkit as well as many others.I know what the experience is like when a library you heavily depend on stops being supported or the support degrades noticeably. I want ACD to continue to improve. I need this library to work, and I hope that we can work together to make that happen for everyone, but if ACD continues to exhibit a lack of timely support, the best option that I see for the entire community is a forked library that does offer that support.

**Comment by vmartinelli** [comment]
@AnthonyMDev I understand your point and if, in the future, I can not maintain this framework anymore, surely you will be one who can take the work forward. In fact, you can do this just now, since the framework is open source and the license is MIT.

On other hand, if you agree and if you can update your PR to avoid conflicts of recent commits, I will approve it and that will be the version for Swift 3.0 until the a new version is out, OK? The framework will need updates to the docs, anyway.

Your help has been invaluable and I would like to thank you very much, but I would like to say that the "correct response" is... There is no correct response. Or each on has its own correct answer.

Finally, I think each of us should be free to act in the best way we can within our understanding of what is right and possible. Freedom (our freedom and the freedom of others), respect and tolerance must always come first.

**Comment by huangy10** [comment]
So, have you guys decided about how to deal with this open-source proj?

**Comment by vmartinelli** [comment]
@huangy10 See the https://github.com/Alecrim/AlecrimCoreData/releases/tag/5.0-beta.1 ;)

**Pull request closed without merging**
