### PR TITLE
Add support for Core Data ApplicationGroup (Extension, Watchkit)

### PR DESCRIPTION
**Pull request by iCodesign**

### CODE REVIEW

**Comment by vmartinelli** [comment]
Hello. Thank you for your contribution.

I do not know if I got it right the modifications and its consequences. Can you explain them better?

**Comment by iCodesign** [comment]
Well, when developing app extensions (such as apple watch apps), you need to share your data with parent app through a [shared container (Apple Documentation)](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW1). 

As to Core Data, we can specify the persistent store path to a shared container through `pesistentStoreContainerUrl = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier(identifier)`.

**Comment by vmartinelli** [comment]
Good solution. Now I understand. Sorry, I have not had time to work with Apple Watch (time, watch... infamous pun). Thank you for the references too. :-)

I would like to ask you to resubmit this PR to `develop` branch. Is it possible?

**Comment by iCodesign** [comment]
:ok_hand:

**Pull request closed without merging**
